sonar.projectKey=SLIIT-CTSE-2026_BookNest-Online-Book-Store
sonar.organization=sliit-ctse-2026
sonar.projectName=api-gateway
sonar.sources=.
sonar.exclusions=node_modules/**,**/*.test.js,**/__tests__/**,coverage/**,dist/**
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.sourceEncoding=UTF-8
