sonar.projectKey=BookNest-Online-Book-Store-product-service
sonar.organization=SLIIT-CTSE-2026
sonar.projectName=product-service
sonar.sources=.
sonar.exclusions=node_modules/**,**/*.test.js,**/__tests__/**,coverage/**,dist/**
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.sourceEncoding=UTF-8
