name: Continuous Integration

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  validate-services:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [customer-service, seller-service, auth-service, product-service, feedback-service, order-service, api-gateway, frontend]

    steps:
      - name: Checkout Code
        uses: actions/checkout@f995f2e6039f9282baf409b14c0d41851b35f570
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@60edb5dd545a775178fba6a0fab3ce0a49617662
        with:
          node-version: 22

      - name: Install Dependencies
        run: npm ci
        working-directory: ./${{ matrix.service }}

      - name: Check for Linting/Formatting
        run: npm run lint --if-present
        working-directory: ./${{ matrix.service }}

      - name: Verify Build
        run: npm run build --if-present
        working-directory: ./${{ matrix.service }}

      - name: SonarCloud Scan
        uses: SonarSource/sonarqube-scan-action@95299e2e0872c51fa247b2143d065d88c52c9a9a
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          projectBaseDir: ./${{ matrix.service }}